apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: thermometers.d2iq.com
spec:
  group: d2iq.com
  version: v1
  names:
    kind: Thermometer
    plural: thermometers
    shortNames:
      - therm
  scope: Namespaced
  additionalPrinterColumns:
    - name: Unit
      type: string
      JSONPath: .spec.unit
    - name: Temperature
      type: string
      JSONPath: .status.temperature
